name: Build with Maven

on:
  push:
    branches:
      - !main
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Java environment
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
          cache: maven

      - name: Build with Maven
        run: mvn clean verify -T4
